--- initialization
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Videos;

CREATE TABLE Videos(
id 	integer		PRIMARY KEY,
title 	varchar(100),
url 	varchar(100) 	NOT NULL,
length 	interval minute
);

CREATE TABLE Reviews(
id 		integer 	PRIMARY KEY,
videoid		integer 	NOT NULL REFERENCES Videos (id) ON UPDATE CASCADE ON DELETE CASCADE,
user_name 	varchar(40),
rating 		integer 	CHECK (rating>=0 AND rating<=5),
message 	varchar(100)
);


-- populate the tables
INSERT INTO Videos
(id, title, url, length)
VALUES
(1, 'How-To Read HTML Files Using Java', 'https://www.youtube.com/watch?v=-aUPknc5z4c', interval '3 minute'),
(2, 'Retrieve text from a html document with XML package of R', 'https://www.youtube.com/watch?v=Mx-Dzu-Q1cE', interval '6 minute'),
(3, 'How to Read HTML from a URL in Java', 'https://www.youtube.com/watch?v=JcZwlpV1rMc', interval '5 minute'),
(4, 'Write HTML file in Java', 'https://www.youtube.com/watch?v=pV0v_3YRQoM', interval '4 minute');


INSERT INTO Reviews
(id, videoid, user_name, rating, message)
VALUES
(1, 1, 'Liam', 4, 'Well explained.'),
(2, 1, 'Emma', 5, 'Simple and effective.'),
(3, 1, 'Olivia', 0, 'OMD, is this a video generated by robot?'),
(4, 2, 'Emma', 2, 'I felt sleepy!'),
(5, 2, 'Olivia', 1, 'hard to follow'),
(6, 4, 'Noah',NULL, 'Cannot open.');

-- query
SELECT 
	v.id as videoID, 
	v.title as videoTitle,
	v.url as videoURL,
	v.length as videoLength,
	r.user_name as userName, 
	r.rating as userRating, 
	r.message
FROM Videos v LEFT JOIN Reviews r
ON v.id=r.videoid;




